apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: dev

resources:
  - sealedsecret.yaml
  - ../../base/frontend
  - ../../base/backend
  - ../../base/policies
  - ../../base/postgres
  - ../../base/ingress
  - ../../base/network
    - ../../base/rbac
  - ../../storage

patches:
  - path: patches/frontend.yaml
  - path: patches/backend.yaml
  - path: patches/postgres.yaml
