apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hotel-booking-api
  name: hotel-booking-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-booking-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hotel-booking-api
    spec:
      containers:
      - image: tchoumidev/hotel-booking-api:1.0.0
        name: hotel-booking-api
        resources: {}
status: {}
