apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-dns-policy
spec:
  rules:
    - name: allow-dns
      match:
        any:
          - resources:
              kinds:
                - Namespace
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - kyverno
                - cilium
                - argocd
      generate:
        apiVersion: cilium.io/v2
        kind: CiliumNetworkPolicy
        name: allow-dns
        namespace: "{{ request.object.metadata.name }}"
        synchronize: true
        data:
          spec:
            endpointSelector: {}
            egress:
              - toEndpoints:
                  - matchLabels:
                      k8s:io.kubernetes.pod.namespace: kube-system
                toPorts:
                  - ports:
                      - port: "53"
                        protocol: UDP
