apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: mutate-default-resources
spec:
  rules:
    - name: set-default-resources
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - prod
                - dev
      mutate:
        patchStrategicMerge:
          spec:
            containers:
              - name: "*"
                (resources):
                  requests:
                    cpu: "100m"
                    memory: "128Mi"
                  limits:
                    cpu: "500m"
                    memory: "512Mi"
