apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: mutate-pod-security
spec:
  rules:
    - name: add-default-security-context
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - argocd
                - kyverno

      mutate:
        foreach:
          - list: "request.object.spec.containers"
            patchStrategicMerge:
              spec:
                containers:
                  - name: "{{ element.name }}"
                    securityContext:
                      allowPrivilegeEscalation: false
                      privileged: false
                      runAsNonRoot: true
                      capabilities:
                        drop:
                          - ALL