---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: default
spec:
  encryptedData:
    password: AgBOAIIErgxxDh1OCAJv9ZZtj2kQSq2wI5TOA5c48iMkQ6nzY3dHzdqYNPVh9zBqOg0S+mRzN1OxRGYEyyVMNrzT1grC/nXygCnXI6F98LznFR8hOAeUMbcOjn77E4l2x9nXQZmV+lTHe4aPL//TdX32Eu34pabvvdiOhpYRxS+392awEYTE8sdNb3fgW3YtXQpWJ/8PIfkHJiNykaPjZlT0Qxs1cnBHz39mC9TNu2meye/N/xpm1i+gPCRFy4PNTpeXqChseLWKFCLU3o2uOBoPjiRcmwqg1vctYyWJM2NZYLKwdKq4/fkPYlPmxpuJu+VxaNTvstM6JB+kQ4joaMtQcUObzFV39uJuLI6YqwC9z+h6qOgJI9QkapZreZdIHuH1eQgS9kzD0dCK0aOhAWRTzuD7uA335xQyX0dASVwsyX0HI31lOgOtTH6uIyeMf6J/kETyOXN0uXfbJUKNLVQFjsboirXN6ylLx/SOG+BuiqJxs84IEHF/imr7jCm8dUMqw33SyzZAh6bdoxWOyHvApmXd+C8YG6NmS9/PhDTLtxKBSIzOhEM0xK2TOwK3YqtbEzXZmnAxgOSJh1e9IzmfgYtz54mPuWOgXaptI0+UawZ+hN0l+Eh4li+e7ECLMn5C3praSfCCHxfgUTU01kAlZESlrnDlEQo4FXlpAlajye9T8JCbks2PT5Qr534Jz9umZqpA
    username: AgAQPRyvnLMiYDewxj+M3m9369T+5aMWi/BucxFvhfXpF/HiefswEV6FgmanJb5ZjZHjPqHEtzh0/Wwm97vbl70U0t2i42IhAqg1pkegbv9M5j6RvyJi8ZQVI6G5QKdQv9uaCI3mZkn9Q1NIqt/+TT+CEWrR8jocY4AUBI1flPQrrYzieUU0ChahROek9lJJl8Cwr30KCp8gh/D0EL5wjeEKuI2imzxQMDHbRCVHmN3ldy6PWLPeClsrd1jhxWzPNLta6G9rjydrNAlaohU/rsTIT1LKEnsX8NmYkBC/3sjUKfOHhlquIT6jrhebt3sXQGBuslIGWr+CbDTKQi/v/N11ZHgyaq0bjjBYhbFM+q0XyvwqTkeBVN2Il4CzarPGAeocZ1xTIozI1bxDYlaDxYkr9Ea4vWebTFipgDuIeaNt3NdEAJV/otmEVOm81rdfWFfX8lGMn0Qf/jBl/Sz9wyHBdGCcXUbKYe2JFLC3V37DLcbtAjxpTcC4C0CvTRBD1I98Dg9XPVn3D1gFcfec7XMsvM9HOltVjCNXxshZ80DUPC9aU8AMV5P2aj1+HWNXQGmU8UGYTpQl8nBgKQGDOFOdC+4WFF3taIQUwKXcJ9LoR3a1jrUKmSbIHSOKR5KJrYyZ39alPwUL6IoRzMsPGZNK6IDpuCP2xq0IO3ELG/oxydv4b4bhvsLijkDjdR0ntMZLZmlalsqvPA==
  template:
    metadata:
      name: postgres-secret
      namespace: default
