apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-dev
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-dev
  hostPath:
    path: /tmp/postgres-dev
    type: DirectoryOrCreate
