apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - dev-pv-def.yaml
  - dev-pvc-def.yaml
  - storageclass-dev.yaml
  # - prod-pv-def.yaml
  # - prod-pvc-def.yaml
  # - storageclass-prod.yaml

  